import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'en_US': {
          "An error occurred while loading the data:":"An error occurred while loading the data:",
          "Data saved successfully!":"Data saved successfully!",
          "An error occurred while saving:":"An error occurred while saving:",
          'Managing "About Us" and FAQs':'Managing "About Us" and FAQs',
          'Basic Information':'Basic Information',
          'Frequently Asked Questions (FAQ)':'Frequently Asked Questions (FAQ)',
          'About the App / Who We Are':'About the App / Who We Are',
          "Contact and Social Media Details":"Contact and Social Media Details",
          "Contact number":"Contact number",
          "WhatsApp number":"WhatsApp number",
          "Facebook link":"Facebook link",
          'e-mail':'e-mail',
          "Instagram link":"Instagram link",
          "Save changes":"Save changes",
          "Add a new question":"Add a new question",
          "Edit FAQ item":"Edit FAQ item",
          "Add a new FAQ":"Add a new FAQ",
          "The Question":"The Question",
          "The Answer":"The Answer",
          "cancellation":"cancellation",
          "Edit":"Edit",
          "Add":"Add",
          "Access Defined !":"Access Defined !",
          "Error":"Error",
          "The Excel file has been successfully created and saved:":"The Excel file has been successfully created and saved:",
          "Export error":"Export error",
          "An error occurred while loading the data:":"An error occurred while loading the data:",
          "Analytics and Business Management Center":"Analytics and Business Management Center",
          "Export to Excel":"Export to Excel",
          "Preparing and saving the Excel file...":"Preparing and saving the Excel file...",
          "Business Growth Recommendations and Analyses 🚀":"Business Growth Recommendations and Analyses 🚀",
          "Key Performance Indicators (KPIs)":"Key Performance Indicators (KPIs)",
          "Total sessions":"Total sessions",
          "guests":"guests",
          "Registered":"Registered",
          "Total searches":"Total searches",
          "Guest Research:":"Guest Research:",
          "Average dwell time":"Average dwell time",
          "minute":"minute",
          "Reaction rate":"Reaction rate",
          "Peak hour":"Peak hour",
          "Visitor at this time":"Visitor at this time",
          "Most searched terms and categories 🔍":"Most searched terms and categories 🔍",
          "Recent visitor and user search log":"Recent visitor and user search log",
          "Visitor activity by time of day (Peak Hours)":"Visitor activity by time of day (Peak Hours)",
          "Distribution of Platforms and Devices (Pie Chart)":"Distribution of Platforms and Devices (Pie Chart)",
          "Bar chart of most-viewed products":"Bar chart of most-viewed products",
          "Product performance using live data":"Product performance using live data",
          "Recent session log and details":"Recent session log and details",
          "There are no recorded searches for this period.":"There are no recorded searches for this period.",
          "Empty search":"Empty search",
          "undefined":"undefined",
          "Source: Guest":"Source: Guest",
          "User (":"User (",
          "user:":"user:",
          "High demand for a specific search term 🔍":"High demand for a specific search term 🔍",
          "Visitors search frequently for":"Visitors search frequently for",
          "You can offer additional products that fall under this name or improve their visibility.":"You can offer additional products that fall under this name or improve their visibility.",
          "The ideal time to send notifications and offers ⏰":"The ideal time to send notifications and offers ⏰",
          "The peak period of visitor activity is at...":"The peak period of visitor activity is at...",
          "It is recommended to schedule flash sales and notifications for this time.":"It is recommended to schedule flash sales and notifications for this time.",
          "The most in-demand and sought-after product 🔥":"The most in-demand and sought-after product 🔥",
          "The Product":"The Product",
          "It receives the highest level of attention for (":"It receives the highest level of attention for (",
          "to watch).":"to watch).",
          "Timeframe:":"Timeframe:",
          "Visits are distributed throughout the 24-hour period.":"Visits are distributed throughout the 24-hour period.",
          "No products have been viewed yet during this period.":"No products have been viewed yet during this period.",
          "Untitled Product":"Untitled Product",
          "EGP":"EGP",
          "There are no product views yet to generate a graph.":"There are no product views yet to generate a graph.",
          "Views":"Views",
          "session":"session",
          "Guest Visitor (Guest)":"Guest Visitor (Guest)",
          "Platform:":"Platform:",
          "Views:":"Views:",
          "It began":"It began",
          "Registered user (":"Registered user (",
          "Adding a new Banar":"Adding a new Banar",
          "Modify the banner":"Modify the banner",
          "Click to select a banner image":"Click to select a banner image",
          "Clickable (OnClick)":"Clickable (OnClick)",
          "Upon activation, the user will be directed to the sections.":"Upon activation, the user will be directed to the sections.",
          "Select the relevant section.":"Select the relevant section.",
          "Uncategorized Section":"Uncategorized Section",
          "cancellation":"cancellation",
          "Please choose an image first":"Please choose an image first",
          "Please select a section when enabling click functionality.":"Please select a section when enabling click functionality.",
          "Failed to upload the image to Cloudinary.":"Failed to upload the image to Cloudinary.",
          "Save changes":"Save changes",
          "Are you sure you want to permanently delete this banner?":"Are you sure you want to permanently delete this banner?",
          "delete":"delete",
          "Add Banner":"Add Banner",
          "There are currently no banners.":"There are currently no banners.",
          "Interactive":"Interactive",
          "Display only":"Display only",
          "Department:":"Department:",
          "Static display image":"Static display image",
          "Error loading categories!":"Error loading categories!",
          "No categories found matching your search.":"No categories found matching your search.",
          "Categories Management":"Categories Management",
          "Manage your store product categories":"Manage your store product categories",
          "Add New Category":"Add New Category",
          "Categories Management":"Categories Management",
          "Manage your store product categories":"Manage your store product categories",
          "Search categories by Arabic or English name...":"Search categories by Arabic or English name...",
          "Delete Category":"Delete Category",
          "Are you sure you want to delete":"Are you sure you want to delete",
          "Cancel":"Cancel",
          "Delete":"Delete",
          "Add New Category":"Add New Category",
          "Edit Category":"Edit Category",
          "Category Image":"Category Image",
          "Error picking image:":"Error picking image:",
          "Click to select Category Image":"Click to select Category Image",
          "Cancel":"Cancel",
          "Save":"Save",
          "Update":"Update",
          "Password reset link sent to your email!":"Password reset link sent to your email!",
          "An error occurred while sending reset link":"An error occurred while sending reset link",
          "An unexpected error occurred":"An unexpected error occurred",
          "Forgot Password?":"Forgot Password?",
          "No worries, enter your registered email and we'll send you a link to reset your password.": "No worries, enter your registered email and we'll send you a link to reset your password.",
          "Email Address":"Email Address",
          "Please enter your email":"Please enter your email",
          "Enter a valid email address":"Enter a valid email address",
          "Send Reset Link":"Send Reset Link",
          "Back to Login": "Back to Login",
          "Check Your Email":"Check Your Email",
          "We sent a password reset link to:":"We sent a password reset link to:",
          "Return to Login":"Return to Login",
          "Didn't receive the email? Try again":"Didn't receive the email? Try again",
          "System Overview Dashboard":"System Overview Dashboard",
          "Real-time analytics and business insights": "Real-time analytics and business insights",
          "Refresh Data":"Refresh Data",
          "System Metrics & Resources": "System Metrics & Resources",
          "Financials & Orders Breakdown":"Financials & Orders Breakdown",
          "Business Growth & Conversion":"Business Growth & Conversion",
          "Welcome Back,":"Welcome Back,",
          "Here is what's happening with your platform today.":"Here is what's happening with your platform today.",
          "System: Online":"System: Online",
          "Today's Visitors":"Today's Visitors",
          "yesterday":"yesterday",
          "Total Customers":"Total Customers",
          "Employees & Staff":"Employees & Staff",
          "Total Products":"Total Products",
          "Total PromoCode":"Total PromoCode",
          "Categories & Sub":"Categories & Sub",
          "Categories":"Categories",
          "Subcategories":"Subcategories",
          "Net Monthly Income":"Net Monthly Income",
          "In:":"In:",
          "Out:":"Out:",
          "Active":"Active",
          "Completed":"Completed",
          "Cancelled":"Cancelled",
          "Monthly Growth":"Monthly Growth",
          "Revenue vs last month":"Revenue vs last month",
          "Avg Order Value":"Avg Order Value",
          "Revenue vs last month":"Revenue vs last month",
          "Across":"Across",
          "total orders":"total orders",
          "Conversion Rate":"Conversion Rate",
          "orders":"orders",
          "sessions":"sessions",
          "Active Orders In Progress":"Active Orders In Progress",
          "No active orders currently in progress.":"No active orders currently in progress.",
          "Order":"Order",
          "Status:":"Status:",
          "Login failed":"Login failed",
          "We were unable to verify the account details; please try again.":"We were unable to verify the account details; please try again.",
          "An error occurred while logging in.":"An error occurred while logging in.",
          "This email address is not registered with us.":"This email address is not registered with us.",
          "The password is incorrect; please check it and try again.":"The password is incorrect; please check it and try again.",
          "The email format is invalid.":"The email format is invalid.",
          "This account has been disabled. Please contact support.":"This account has been disabled. Please contact support.",
          "The email or password is incorrect.":"The email or password is incorrect.",
          "Attempts have been temporarily blocked due to too many incorrect attempts. Please try again later.":"Attempts have been temporarily blocked due to too many incorrect attempts. Please try again later.",
          "login failed":"login failed",
          "Unexpected error":"Unexpected error",
          "Make sure you are connected to the Internet and try again.":"Make sure you are connected to the Internet and try again.",
          "Failed to retrieve user data.":"Failed to retrieve user data.",
          "Failed to log out":"Failed to log out",
          "Welcome Back!":"Welcome Back!",
          "DesignLand Admin Dashboard\nManage orders, products & customized gifts": "DesignLand Admin Dashboard\nManage orders, products & customized gifts",
          "DesignLand Dashboard": "DesignLand Dashboard",
          "Sign In":"Sign In",
          "Enter your credentials to access the admin panel":"Enter your credentials to access the admin panel",
          "Password":"Password",
          "Please enter your password":"Please enter your password",
          "Password must be at least 6 characters":"Password must be at least 6 characters",
          "Forgot Password?":"Forgot Password?",
          "Login to Dashboard":"Login to Dashboard",
          "Home":"Home",
          "Categories":"Categories",
          "Orders":"Orders",
          "Reports":"Reports",
          "Products":"Products",
          "Staff":"Staff",
          "Users":"Users",
          "Analytics":"Analytics",
          "About":"About",
          "Banners":"Banners",
          "PromoCode":"PromoCode",
          "Search...":"Search...",
          "Record New Expense":"Record New Expense",
          "Record New Payment Deposit":"Record New Payment Deposit",
  "Notes (e.g. Shipping, Printing, Packaging)":"Notes (e.g. Shipping, Printing, Packaging)",
  "Notes (e.g. Bank Transfer, Instapay, Cash)":"Notes (e.g. Bank Transfer, Instapay, Cash)",
            "Expense":"Expense",
            "Payment":"Payment",
            "recorded successfully!":"recorded successfully!",
          "Save Transaction":"Save Transaction",
          "Financial Summary":"Financial Summary",
          "Total Price:":"Total Price:",
          "Promo Code:":"Promo Code:",
          "Net Profit:":"Net Profit:",
          "Total Paid":"Total Paid",
          "Remaining":"Remaining",
          "Expenses":"Expenses",
          "Add Payment":"Add Payment",
          "Add Expense":"Add Expense",
          "Customer Info":"Customer Info",
          "Customer Name:":"Customer Name:",
          "Order Date:":"Order Date:",
          "Address:":"Address:",
          "Order Items & Details":"Order Items & Details",
          "Notes:":"Notes:",
          "Admin Dynamic Specifications:":"Admin Dynamic Specifications:",
          "Payments History":"Payments History",
          "No payments yet.":"No payments yet.",
          "Expenses History":"Expenses History",
          "No expenses yet.":"No expenses yet."
        },
        'ar_DZ': {

        },
      };
}